### ISSUE TITLE
Custom DNS not persistent between restarts

### ISSUE THREAD

**Issue by Mryck** [hassio-addons/addon-pi-hole#15] opened 2017-12-07 20:10 UTC
# Problem/Motivation

Hi, I have set a custom DNS in the settings of pi-hole but when I restart pi-hole Add-on, the settings still show the custom one but graphs show that it's google DNS in use.

## Expected behavior

Keep the custom DNS when restart

## Actual behavior

The Custom DNS is overwrite by google's DNS

## Steps to reproduce

Uncheck the google's DNS in the settings of pi-hole main panel, add custom dns, browse some webpage with ads to record some values for graphs, restart the add-on and browse again some web-page to see that it's the google's dns in use.

**Comment by frenck** [comment] 2017-12-07 20:26
Thank you for reporting this one @Mryck!
I will check and see if I can reproduce this one.

**Comment by frenck** [comment] 2017-12-07 21:42
I've tried you're reproduction scenario on the upcoming version of the add-on and was not able to reproduce it. 👍 

I'll leave this one open until it is fixed in #13

**Comment by frenck** [comment] 2017-12-08 21:51
v0.4.0 is going to be released, which does not have this issue.

**Closed by frenck** 2017-12-08 21:51 UTC
Labels: Bug
