### ISSUE TITLE
Refused to display  XXX URL   in a frame because it set 'X-Frame-Options' to 'sameorigin'.

### ISSUE THREAD

**Issue by Makr91** [hassio-addons/addon-pi-hole#12] opened 2017-11-28 07:36 UTC
# Problem/Motivation
Refused to display 'https://farmercity.m4kr.net:80/admin/index.php' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
> (Why the issue was filed)
Potential change to Hassio addon repo to allow x-frame-origin to allow from any
## Expected behavior
to be allowed from any source
> (What you expected to happen)

## Actual behavior
Blocked due to CSP policy
https://i.imgur.com/0cSAl9P.png

> (What actually happened)
using this config:

{
  "log_level": "info",
  "password": "",
  "update_lists_on_start": false,
  "web_port": 80,
  "dns_port": 53,
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "interface": "",
  "ipv6": true,
  "ipv4_address": "farmercity.m4kr.net",
  "ipv6_address": "ha.m4kr.net",
  "virtual_host": "farmercity.m4kr.net"
}

## Steps to reproduce
after adding domain to 
> (How can someone else make/see it happen)

## Proposed changes

add x-fram-allow all or wildcard all

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment] 2017-11-28 08:37
Hi there @Makr91, thank you for this issue.
This issue is a duplicate of #10, therefore closing this issue.

**Closed by frenck** 2017-11-28 08:37 UTC
Labels: Bug, Duplicate
