### ISSUE TITLE
Network overview: click on ip of a client opens a new window with a wrong url

### ISSUE THREAD

**Issue by deluxestyle** [hassio-addons/addon-pi-hole#96] opened 2019-09-15 19:49 UTC
# Problem/Motivation

> wrong url in a new tap when I click on a client ip within the network section of pi hole
https://hass.io:8123/admin/queries.php?client=192.168.200.27

## Expected behavior

> it should open in the same tab within the pi hole interface the query log section with filter on the clicked ip

**Comment by sinclairpaul** [comment] 2019-09-15 20:13
Duplicate of #92

**Closed by sinclairpaul** 2019-09-15 20:13 UTC
